import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google'
import { Card } from "@/components/Card";
import React from 'react';

const poppins = Poppins({ 
  subsets: ['latin'],
weight: ['100','200','300','400','500','600','700','800','900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        {/* Link para o Font Awesome CDN */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          integrity="sha512-<integrity-hash>"
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body
        className={poppins.className}
      >
        <Card/>
        {children}
      </body>
    </html>
  );
}